# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '>= 13.0.3'

# Application dependencies
gem 'dry-system', '>= 0.17.0'
gem 'dry-struct', '>= 1.4.0'
gem 'dry-transaction', '>= 0.13.0'
gem 'dry-types', '~> 1.5.0'
gem 'dry-validation', '>= 1.6.0'
gem 'dry-monads', '>= 1.3.5'

# Web
gem 'roda', '>= 3.40'
gem 'puma', '>= 5.2.0'
gem 'rack', '>= 2.2.3'

# Database persistence
gem 'sequel', '>= 5.4.0'
# uncomment this to get PG perfomance boost
gem 'sequel_pg', '>= 1.14.0'
gem 'influxdb', '>= 0.8.0'
gem 'redis', '>= 4.2.5'

gem 'http', '>= 4.4.1'

gem 'sentry-ruby', '>= 4.1.5'

group :development, :test do
  gem 'pry-byebug', platform: :mri

  gem 'rubocop', '>= 1.9', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-sequel', require: false
  gem 'rubocop-rake', require: false
end

group :test do
  gem 'factory_bot', '>= 6.1.0'
  gem 'database_cleaner', '>= 1.8.5'
  gem 'rspec', '>= 3.1.0'
  gem 'vcr', '>= 6.0.0'
  gem 'webmock', '>= 3.1.11'
end
